import type { ReactNode } from "react";
import Link from "next/link";
import { EndpointCard, DirectoryMaintainerSnippet } from "@/components/endpoint-card";
import { SiteFooter } from "@/components/site-footer";
import { VENDING_SERVICES } from "@/lib/services/registry";
import { CAIP_NETWORK, serverEnv } from "@/lib/env";
import type { VendingCategory, VendingService } from "@/lib/services/types";

function categoryOf(s: VendingService): VendingCategory {
  return s.category ?? "atom";
}

function Section({
  title,
  eyebrow,
  children,
}: {
  title: string;
  eyebrow: string;
  children: ReactNode;
}) {
  return (
    <section className="mt-12">
      <p className="text-sm uppercase tracking-widest text-emerald-400">{eyebrow}</p>
      <h2 className="mt-2 text-2xl font-semibold text-zinc-50">{title}</h2>
      <div className="mt-5 grid gap-5">{children}</div>
    </section>
  );
}

export default function HomePage() {
  const network = CAIP_NETWORK[serverEnv.X402_NETWORK_MODE];
  const baseUrl = (serverEnv.PUBLIC_BASE_URL ?? "https://vending-machine-seven.vercel.app").replace(
    /\/$/,
    "",
  );
  const enabled = VENDING_SERVICES.filter((s) => s.enabled);
  const bundles = enabled.filter((s) => categoryOf(s) === "bundle");
  const premium = enabled.filter((s) => categoryOf(s) === "premium");
  const atoms = enabled.filter((s) => categoryOf(s) === "atom");

  return (
    <>
      <main className="mx-auto max-w-6xl px-6 py-12">
        <section className="relative overflow-hidden rounded-3xl border border-emerald-500/20 bg-[radial-gradient(circle_at_top_left,rgba(16,185,129,0.20),transparent_34%),linear-gradient(135deg,rgba(24,24,27,0.95),rgba(9,9,11,0.98))] p-6 shadow-2xl shadow-emerald-950/20 sm:p-10">
          <div className="max-w-3xl">
            <p className="text-sm uppercase tracking-widest text-emerald-300">
              x402 V2 · Base bundler hub
            </p>
            <h1 className="mt-3 text-4xl font-semibold tracking-tight text-zinc-50 sm:text-5xl">
              Multi-step agent jobs. One USDC payment.
            </h1>
            <p className="mt-4 text-base leading-7 text-zinc-300">
              Pay-per-call HTTP utilities and AI-ready research tools, settled in USDC on Base — no
              accounts required. Network {network} · {enabled.length} live tools · bundles first,
              live upstream only, fail-closed with no settle on handler errors.
            </p>
            <div className="mt-6 flex flex-wrap gap-3 text-sm">
              <Link
                href="/test"
                className="rounded-xl bg-emerald-400 px-4 py-2.5 font-semibold text-zinc-950 transition hover:bg-emerald-300"
              >
                Try wallet payment
              </Link>
              <Link
                href="/.well-known/agent-services.json"
                className="rounded-xl border border-zinc-700 bg-zinc-950/40 px-4 py-2.5 text-zinc-200 transition hover:border-zinc-500"
              >
                Agent catalog
              </Link>
              <Link
                href="/api/openapi.json"
                className="rounded-xl border border-zinc-700 bg-zinc-950/40 px-4 py-2.5 text-zinc-200 transition hover:border-zinc-500"
              >
                OpenAPI
              </Link>
            </div>
          </div>
        </section>

        <DirectoryMaintainerSnippet baseUrl={baseUrl} />

        <Section title="Bundles for multi-signal agents" eyebrow="Go-to endpoints">
          {bundles.map((s) => (
            <EndpointCard key={s.slug} service={s} baseUrl={baseUrl} featured />
          ))}
        </Section>

        {premium.length > 0 && (
          <Section title="Premium research tools" eyebrow="Higher-value calls">
            {premium.map((s) => (
              <EndpointCard key={s.slug} service={s} baseUrl={baseUrl} />
            ))}
            <p className="text-xs leading-5 text-zinc-500">
              Kronos forecast outputs are generated by an open-source model and are not financial
              advice, investment recommendations, or trading signals. Accuracy is not guaranteed. Read
              the{" "}
              <Link className="text-emerald-400 underline" href="/disclaimer">
                Research Disclaimer
              </Link>
              .
            </p>
          </Section>
        )}

        <Section title="Utility atoms" eyebrow="Single-purpose paid endpoints">
          {atoms.map((s) => (
            <EndpointCard key={s.slug} service={s} baseUrl={baseUrl} />
          ))}
        </Section>

        <section className="mt-12 space-y-2 text-sm text-zinc-400">
          <p>
            Discovery:{" "}
            <Link className="text-emerald-400 underline" href="/.well-known/agent-services.json">
              agent-services.json
            </Link>
            ,{" "}
            <Link className="text-emerald-400 underline" href="/.well-known/x402">
              x402
            </Link>
            ,{" "}
            <Link className="text-emerald-400 underline" href="/api/openapi.json">
              OpenAPI
            </Link>
          </p>
          <p className="text-xs text-zinc-600">
            Micropayments are final when settled. Use is subject to our{" "}
            <Link className="underline hover:text-zinc-400" href="/terms">
              Terms
            </Link>
            , including{" "}
            <Link className="underline hover:text-zinc-400" href="/terms#acceptable-use">
              Acceptable Use
            </Link>
            .
          </p>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}
